# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      mkdir build
      cd build
      cmake ..
      make
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      mkdir build
      cd build
      cmake ..
  - task: VSBuild@1
    inputs:
      solution: 'OpenCOLLADA.sln' 

